const Biodata = {
  rasimas: [
    "Dr. Rasimas has a Jesuit university background in biochemistry, mathematics, and philosophy. He completed the Medical Scientist Training Program at Penn State University, earning a Ph.D. in chemical biology (2002) and M.D. (2003). After Psychiatry residency training at the Mayo Clinic in Rochester, Minnesota, he was a clinical fellow at the National Institute of Mental Health, training in consultation-liaison psychiatry, bioethics, and clinical research. He received the institute’s highest honor for clinical care – the Hannah Cashman Memorial Award. Dr. Rasimas has studied psychoanalytic psychotherapy at the Minnesota Psychoanalytic Society and Institute and the Washington School of Psychiatry. He served as a C - L psychiatrist for Milton S. Hershey Medical Center and remains on faculty for the Penn State College of Medicine there. He completed the critical care-based medical toxicology fellowship at Penn State, obtained board certification in addiction medicine, and then returned to Bethesda, Maryland to the National Institutes of Health where he joined the Undiagnosed Diseases Program and the Intramural Research Program to oversee clinical trials in mood and anxiety disorders. He is also a Fellow of the Academy of Psychosomatic Medicine, the American College of Medical Toxicology, and the American College of Psychiatrists.",
    "Dr. Rasimas has a background in emergency psychiatry integrating multidisciplinary education into clinical work in toxicology and mental health. Currently, he is the Director of C – L Psychiatry at Hennepin County Medical Center in Minneapolis, Minnesota. He teaches medical students, residents, fellows, and candidates in psychoanalysis across the Twin Cities region. He is a Full Professor at the University of Minnesota, pursuing an academic medical career at the interface of psychosomatic medicine, medical toxicology, bioethics, and psychoanalysis with a primary clinical interest in the phenomenology of suicide. Dr. Rasimas has developed an interest in the public health problem of suicide and the personalized care of patients who struggle with urges to harm themselves in various ways.",
  ],
  jaques: [
    "Dr. Jaques is a passionate advocate for enhanced mental health. She obtained a Bachelor of Science (Hons) Degree from Universiti Sains Malaysia in 1987 and a Master of Arts Degree in Psychology in 1997 from the Ateneo De Manila University Philippines. In 2018, she completed her PhD in Clinical Psychology where the focus of her dissertation was on shame as a trait in personality pathology. As a consultant clinical psychologist with her own private practice Integrated Psychology Network Sdn Bhd which she founded in 1998, her clients include individuals and families from diverse cultures, across the world, living in Malaysia and around Asia. She works with couples from pre-marriage issues to marital conflicts as well as support for those who have experienced the trauma of divorce and child custody.",
    "Dr. Jaques is skilled in psychological assessment, and is experienced in the areas of employee assistance programs, coaching and counseling, crisis management, career direction and customized training. She is certified in Critical Incidence Stress Management (CISM) both from the CISM Institute as well as the UN Department of Safety and Security, and has supported a few multinational organizations as well as individuals who have experienced trauma and crisis. As a National Psychologist for Medicine Sans Frontiers (Doctors without Borders), she trained and supervised groups of volunteers for psychosocial and mental health support for survivors of crises and trauma including refugees at outreach clinics as well as detention centers in Malaysia. She was also selected by the United Nations Department of Safety and Security to be trained and certified in critical incidents stress management (“CISM”) for support in the Asian region.",
    "From 2000 to 2001, Dr. Jaques worked as the international expert in child counseling on behalf of the United Nations Office for Project Services (UNOPS) for a United Nations Development Program (UNDP) project based in Bangladesh. During her tenure, she organized training for trainers to offer counseling services and psychosocial development for the street children in Bangladesh. Her role included networking with both local and international organizations while looking into issues on government policy with the need to formulate strategies for implementation of child rights based on the UN Convention on the Rights of the Child. Since her return to Malaysia in 2002, she has guest lectured on gender diversity at Help University as well as for University Kebangsaan Malaysia’s undergraduate students in forensic science on gender-based violence (domestic violence, rape, sexual harassment, and childhood sexual abuse). She has also been a guest lecturer at Monash University and Nottingham University and provided training to various NGOs and organizations. In addition, Dr Jaques is a certified trainer for the Malaysian Human Resource Development Fund.",
  ],
  azlinda: [
    "Professor Dr. Azlinda has been the Head of the Social Work Program at the School of Social Sciences in Universiti Sains Malaysia (USM) since 2012. She is Malaysia’s first Social Work Professor, currently leading the charge for the professional recognition of social workers in the country, and is also actively involved internationally in advocating for social work education and practice.",
    "Dr Azlinda obtained her Bachelor of Social Science (Social Work) from USM, and Master of Social Work from Grand Rapids, Michigan. She was among the few who were selected and awarded the Fulbright Scholarship to pursue her Doctorate of Philosophy in Clinical Social Work from New York University in the US. Her field of expertise includes social work practice, social work education, supervision in social work and social work research.",
    "She is also the Honorary Secretary of the Malaysian AIDS Council (MAC) and the Convener of the AIDS Action and Research Group (AARG) in USM. For her contribution in rehabilitation of inmates in the country, she was awarded Pingat Bakti Setia by the Ministry of Home Affairs, Malaysia.",
    "Dr. Azlinda chairs the National Joint Council Committee on Social Work Education, is an executive committee member of the Malaysian Association of Social Workers (MASW), and a member of the Steering Committee in drafting the Malaysian Social Worker’s Act. She also sits as a member of the Malaysian Accreditation Agency (MQA) for the social work program. Several public universities have also appointed Dr. Azlinda as a member of their Board of Studies for the development of their social work programs. At the international level, Dr. Azlinda has jointly collaborated in numerous research and publications. She was recently appointed a Visiting Research Fellow of the School of Social Care and Policy, Bournemouth University, United Kingdom, in recognition of her contributions in the field, both nationally and internationally. Her research areas include issues of sexuality among adolescents and children; pregnancy among adolescents; family institutions and community development; poverty; juveniles; drug and substance abuse, HIV and AIDS related issues.",
  ],
};

export default Biodata;
