const Biodata = {
  rasimas: [
    "Dr. Rasimas has a Jesuit university background in biochemistry, mathematics, and philosophy. He completed the Medical Scientist Training Program at Penn State University, earning a Ph.D. in chemical biology (2002) and M.D. (2003). After Psychiatry residency training at the Mayo Clinic in Rochester, Minnesota, he was a clinical fellow at the National Institute of Mental Health, training in consultation-liaison psychiatry, bioethics, and clinical research. He received the institute’s highest honor for clinical care – the Hannah Cashman Memorial Award. Dr. Rasimas has studied psychoanalytic psychotherapy at the Minnesota Psychoanalytic Society and Institute and the Washington School of Psychiatry. He served as a C - L psychiatrist for Milton S. Hershey Medical Center and remains on faculty for the Penn State College of Medicine there. He completed the critical care-based medical toxicology fellowship at Penn State, obtained board certification in addiction medicine, and then returned to Bethesda, Maryland to the National Institutes of Health where he joined the Undiagnosed Diseases Program and the Intramural Research Program to oversee clinical trials in mood and anxiety disorders. He is also a Fellow of the Academy of Psychosomatic Medicine, the American College of Medical Toxicology, and the American College of Psychiatrists.",
    "Dr. Rasimas has a background in emergency psychiatry integrating multidisciplinary education into clinical work in toxicology and mental health. Currently, he is the Director of C – L Psychiatry at Hennepin County Medical Center in Minneapolis, Minnesota. He teaches medical students, residents, fellows, and candidates in psychoanalysis across the Twin Cities region. He is a Full Professor at the University of Minnesota, pursuing an academic medical career at the interface of psychosomatic medicine, medical toxicology, bioethics, and psychoanalysis with a primary clinical interest in the phenomenology of suicide. Dr. Rasimas has developed an interest in the public health problem of suicide and the personalized care of patients who struggle with urges to harm themselves in various ways.",
  ],
  jaques: [
    "Dr. Jaques is a passionate advocate for enhanced mental health. She obtained a Bachelor of Science (Hons) Degree from Universiti Sains Malaysia in 1987 and a Master of Arts Degree in Psychology in 1997 from the Ateneo De Manila University Philippines. In 2018, she completed her PhD in Clinical Psychology where the focus of her dissertation was on shame as a trait in personality pathology. As a consultant clinical psychologist with her own private practice Integrated Psychology Network Sdn Bhd which she founded in 1998, her clients include individuals and families from diverse cultures, across the world, living in Malaysia and around Asia. She works with couples from pre-marriage issues to marital conflicts as well as support for those who have experienced the trauma of divorce and child custody.",
    "Dr. Jaques is skilled in psychological assessment, and is experienced in the areas of employee assistance programs, coaching and counseling, crisis management, career direction and customized training. She is certified in Critical Incidence Stress Management (CISM) both from the CISM Institute as well as the UN Department of Safety and Security, and has supported a few multinational organizations as well as individuals who have experienced trauma and crisis. As a National Psychologist for Medicine Sans Frontiers (Doctors without Borders), she trained and supervised groups of volunteers for psychosocial and mental health support for survivors of crises and trauma including refugees at outreach clinics as well as detention centers in Malaysia. She was also selected by the United Nations Department of Safety and Security to be trained and certified in critical incidents stress management (“CISM”) for support in the Asian region.",
    "From 2000 to 2001, Dr. Jaques worked as the international expert in child counseling on behalf of the United Nations Office for Project Services (UNOPS) for a United Nations Development Program (UNDP) project based in Bangladesh. During her tenure, she organized training for trainers to offer counseling services and psychosocial development for the street children in Bangladesh. Her role included networking with both local and international organizations while looking into issues on government policy with the need to formulate strategies for implementation of child rights based on the UN Convention on the Rights of the Child. Since her return to Malaysia in 2002, she has guest lectured on gender diversity at Help University as well as for University Kebangsaan Malaysia’s undergraduate students in forensic science on gender-based violence (domestic violence, rape, sexual harassment, and childhood sexual abuse). She has also been a guest lecturer at Monash University and Nottingham University and provided training to various NGOs and organizations. In addition, Dr Jaques is a certified trainer for the Malaysian Human Resource Development Fund.",
  ],
  azlinda: [
    "Professor Dr. Azlinda has been the Head of the Social Work Program at the School of Social Sciences in Universiti Sains Malaysia (USM) since 2012. She is Malaysia’s first Social Work Professor, currently leading the charge for the professional recognition of social workers in the country, and is also actively involved internationally in advocating for social work education and practice.",
    "Dr Azlinda obtained her Bachelor of Social Science (Social Work) from USM, and Master of Social Work from Grand Rapids, Michigan. She was among the few who were selected and awarded the Fulbright Scholarship to pursue her Doctorate of Philosophy in Clinical Social Work from New York University in the US. Her field of expertise includes social work practice, social work education, supervision in social work and social work research.",
    "She is also the Honorary Secretary of the Malaysian AIDS Council (MAC) and the Convener of the AIDS Action and Research Group (AARG) in USM. For her contribution in rehabilitation of inmates in the country, she was awarded Pingat Bakti Setia by the Ministry of Home Affairs, Malaysia.",
    "Dr. Azlinda chairs the National Joint Council Committee on Social Work Education, is an executive committee member of the Malaysian Association of Social Workers (MASW), and a member of the Steering Committee in drafting the Malaysian Social Worker’s Act. She also sits as a member of the Malaysian Accreditation Agency (MQA) for the social work program. Several public universities have also appointed Dr. Azlinda as a member of their Board of Studies for the development of their social work programs. At the international level, Dr. Azlinda has jointly collaborated in numerous research and publications. She was recently appointed a Visiting Research Fellow of the School of Social Care and Policy, Bournemouth University, United Kingdom, in recognition of her contributions in the field, both nationally and internationally. Her research areas include issues of sexuality among adolescents and children; pregnancy among adolescents; family institutions and community development; poverty; juveniles; drug and substance abuse, HIV and AIDS related issues.",
  ],
  guibord: [
    "Dr. Guibord, is a Licensed Psychologist with 20 years of experience in private practice providing psychoanalytic psychotherapy and psychoanalysis. His training consists of a doctorate in clinical psychology from Wheaton College graduate school, and a certificate of graduation from the Minnesota Psychoanalytic Institute, affiliate of the American Psychoanalytic Association.  In addition to seeing patients, he teaches Object Relations Theory at his local institute in Minnesota, with an emphasis on the writings of the Pediatrician/Psychoanalyst Donald Winnicott. He has a special interest in the integration of philosophy and psychology, and especially the writings of Albert Camus, as is reflected in his contribution to this panel on suicide."
  ], 
  halim: [
    "Dato’ Halim is a dynamic and noted figure in the field of counseling in Malaysia. Aside from a B.Ed. (Hons.) in Counseling from UPM; M.Sc. in Educational Psychology & Counseling from Indiana University, Bloomington, USA; and a Ph.D. focusing on Drug Addiction Counseling from UiTM, he has attained a vast knowledge of counseling from his experiences as a school counselor, associate professor of counseling in USIM, Director of JPA’s Psychology Management Division and Director-General of the National Anti-Drug Agency. During his years in service, he educated school, human resource and addiction counselors; developed training programs, psychometric assessment and screening tools for human resource management; conducted substantial research and improved on counseling-related policies and practices.",
    "Dato’ Halim has been a key figure in the Malaysian Counseling Association (PERKAMA) for two decades. As the current President, he is resolutely leading PERKAMA in furthering counselors’ professionalism and career paths, organizing local and international counseling conventions, assisting the government in developing the National Counseling Policy, and advocating online counseling to meet the challenges of the present global pandemic. Under his leadership, PERKAMA has made significant strides, including the establishment of the National Council for Counseling Educators and the Young Counseling Scholars, both concerned with the training of counselors in the country. Halim was instrumental in forming MALINDO, the Malaysian-Indonesian counseling partnership which has resulted in numerous joint conferences and workshops held in both countries.",
    "To date, Dato’ Dr. Halim has produced more than 50 books, journal articles and reference materials on counseling and drug addiction-related matters. He has presented at various international conferences and won medals at local and international events for his research-based innovations. Even in retirement, Halim is much sought after as a speaker and consultant. He tirelessly continues to promote the improvement of counseling efforts in Malaysia and abroad, recently initiating the formation of the ASEAN Counseling Network (ASCON) in the hopes of building even greater international collaboration in the region."
  ], 
  karim: [
    "Dr. Raj Abdul Karim has dedicated her lifetime to promoting the health and well-being of women, children and families and has been the prime mover of many policies and programs that are in place today in a career spanning over 4 decades. In her early years as a medical officer in the Ministry of Health, Dr Raj was entrusted with developing Malaysia’s maternal and child health services. Under her leadership in the 1970’s and 1980’s, the Maternal and Child Health Services of Malaysia steadily expanded, with major interventions introduced, resulting in declines in Malaysia’s maternal and infant mortality, and that gained international recognition. Subsequently, she was the Director of the Public Health Institute, Ministry of Health in 1989 and Director General of National Population and Family Development Board in 1992.",
    "Dr. Raj has held many positions throughout her career, among which were: Director of the Public Health Institute, Ministry of Health; Director General of National Population and Family Development Board; and Regional Director of the International Planned Parenthood Federation, East and South East Asia & Oceania Region. In 2002, Dr Raj was appointed by the King as a Commissioner to the National Human Rights Commission Malaysia (SUHAKAM). During her 8-year term to 2010, she initiated work on the protection of the rights of women and children and on Human Trafficking, leading to the national legislation in 2007 and the formation of the Council on Anti Trafficking of Persons of which she was a member from 2008–2015. She received the United Nations Malaysia Award in 2008 and was the moderator of ECPAT International Assembly from 2014–2016. In December 2019 she received the Patron's award from the Malaysian AIDS Foundation for her work on Sexual and Reproductive Health and Rights and HIV and AIDS for women and children.",
    "Today, she continues her contribution as President of the Malaysian Council of Child Welfare, Chair of End CSEC Network Malaysia (ECPAT Malaysia), Vice President of Federation Reproductive Health Associations Malaysia (FRHAM), 2nd Vice President International of Pan Pacific & Southeast Asia Women’s Association (PPSEAWA) and Chair of Malaysian Society of Association Executives (MSAE)."
  ],
  louis: [
    "Ms. Larissa Ann is a litigation Lawyer and Human Rights activist. She currently co-heads the law firm, Messrs. Azri, Lee Swee Seng & Co.’s Pro Bono Unit together with its managing partner. Larissa Ann graduated from University of Reading, UK with a Bachelor of Law (Hons). She was admitted as a Barrister-at-Law (Middle Temple) in 2014 and to the Malaysian Bar in 2016. She handles constitutional law-related matters pertaining to statelessness, religious freedom and enforced disappearances. This unit is one of a kind in Malaysia and is presently changing lives one case at a time. She values the importance of getting into the trenches with her clients and tenaciously fighting for them.",
    "She has represented the United Nations High Commissioner for Refugees–Malaysia (UNHCR–Malaysia), Human Rights Commission of Malaysia (SUHAKAM), Bar Council of Malaysia and various NGOs on human rights issues. In 2019, she was selected to be a Fellow on the Professional Fellows OnDemand Program entitled “Religious Freedom and Interfaith Dialogue Exchange” in the USA, where she represented Malaysia. Besides that, she has acted in complex divorce, defamation, contractual, employment and constitutional matters. She is currently the youngest appointed head of 2 WGs in the Bar Council's Human Rights Committee; specifically \"Statelessness & Citizenship Rights\" & \"Empowering Young Lawyers\"."
  ],
  elisha: [
    "Rev. Elisha Satvinder is the co-founder of Dignity for Children Foundation. Although birthed from the church New Covenant Community which he and his wife Petrina pioneered in 1995, the work of Dignity has taken on a life of its own. For the past 20 years, Dignity has been dedicated to providing quality education and care to the urban poor and refugees in Kuala Lumpur. Dignity, the first Montessori school for the poor in South East Asia, is modelled on providing holistic development, all the while being grounded in real-life experience. Elisha and Petrina strongly believe that education can and must take place beyond the four walls of a classroom; the education of the mind must go alongside education of the hand and heart. This is evident in the transformational enterprises of Dignity that break down the wall between community and school. Since its start, Dignity has helped to educate and transform over 7,000 underprivileged children. In November 2015, Dignity for Children had the great honor of hosting the President of the United States, Barack Obama.",
    "Elisha has a great passion and heart to see a national transformation and to raising the next generation, especially in caring for the marginalized. He has spoken and taught extensively both locally and overseas, including in Australia, USA, Canada, Singapore, Indonesia and the Philippines. He is often invited to lecture in Bible schools, especially on Scriptural injunctions on serving the poor, and at local institutions on various aspects of Social Responsibility and Social Ethics. He is currently a council member and Honorary Secretary of the National Evangelical Christian Fellowship (NECF), a Board member of Tung Ling Seminary where he lectures each semester, and the Chair of Children at Risk Network in Malaysia. In 2007, he served as the Director of Mobilization for Celebration of Hope Malaysia (An Initiative of the Billy Graham Evangelistic Association). He had also served on the council of the Malaysian Consultative Council of Buddhism, Christianity, Hinduism, Sikhism and Taoism.  Rev. Elisha is father to 2 biological daughters and 18 fostered children.",
    "To quote him, “Our journey is a journey of thousands of children believing, desiring, and reaching out to take hold of a secure future through education to break the cycle of poverty for themselves and their families.”"
  ],
  petrina: [
    "Ms. Petrina Satvinder is the co-founder and current Chief Executive Officer and Principal of Dignity for Children Foundation. In 1995, Petrina and her husband Rev. Elisha pioneered the New Covenant Community Church. The church was active in providing care to the poor communities in the vicinity of the church. Her heart became burdened for the children who were illiterate and left behind that she encountered in Sentul. Thus, began the work of Dignity. To date, the lives of over 20,000 underprivileged children have been changed as a result of Dignity’s vision that the education of the mind must accompany the education of the hand and heart.",
    "Petrina holds two Master degrees: the Master of Arts in Holistic Child Development from the Malaysian Baptist Seminary, Malaysia, and Master of Education with majors in Curriculum and Pedagogy from the University of Southern Queensland. She also possesses an International Diploma in Montessori Pedagogy from Montessori Centre International, UK, as well as Lower and Upper Elementary Montessori Teaching Diploma from the North America Montessori Center. Petrina is passionate about continuously learning, just as she is about implementing child-directed learning through Montessori’s philosophy.",
    "Petrina's strongly believe that education can and must take place beyond the four walls of a classroom, that education of the mind must go alongside education of the hand and heart. This is evident in the transformational enterprises of Dignity that breaks down the wall between community and school. Her current focus is on building a model of transformative youth education grounded in community building, natural agriculture and skills development. The farm school aim is provide a place where the children and youth connect skills and knowledge (a fusion of holistic Education) from a wellspring of sources and experiences, combining practical skills and theory in a farm setting.  In setting up the Farm school, both Elisha and Petrina have taken Dignity's urban mission to the disadvantaged into the rural disadvantaged communities."
  ]
};

export default Biodata;
